import type { UiItem } from "@/types/ui-item";

export const mockUiItems: UiItem[] = [
  {
    id: "ui-001",
    slug: "scroll-driven-landing-hero",
    title: "Scroll Driven Landing Hero",
    description: "スクロールに合わせてコピーとカードが奥行きを持って切り替わるLPヒーロー。",
    longDescription:
      "Web制作会社向けのポートフォリオで最初に見せたい、余白・タイポグラフィ・視差表現を組み合わせたランディングページ演出です。",
    category: "lp-animation",
    tags: ["hero", "scroll", "landing-page"],
    emotionTags: ["制作会社っぽい", "LP向き", "かっこいい"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    difficulty: 4,
    thumbnailUrl: "/window.svg",
    demoType: "section",
    status: "published",
    isFeatured: true,
    createdAt: "2026-05-21",
    updatedAt: "2026-05-21",
    implementationNotes: [
      "スクロール量に合わせてテキストとカードの透明度・位置を変化させる。",
      "スマホでは視差量を抑え、読みやすさを優先する。",
    ],
    learningPoints: ["LP演出の情報設計", "モーション量の調整", "レスポンシブ時の軽量化"],
    improvementIdeas: ["GSAP版の比較実装", "実画像を使ったブランドサイト風バリエーション"],
  },
  {
    id: "ui-002",
    slug: "magnetic-button",
    title: "Magnetic Button",
    description: "ポインターに吸い寄せられるように動く、触って気持ちいいCTAボタン。",
    category: "micro-interaction",
    tags: ["button", "hover", "focus"],
    emotionTags: ["気持ちいい", "ぬるっと動く", "実務向き"],
    technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    difficulty: 3,
    thumbnailUrl: "/file.svg",
    demoType: "component",
    status: "published",
    isFeatured: true,
    createdAt: "2026-05-21",
    updatedAt: "2026-05-21",
    implementationNotes: ["マウス移動量を安全な範囲に制限する。", "キーボードフォーカス時も視覚状態を出す。"],
    learningPoints: ["マイクロインタラクション", "フォーカス状態", "モーションの抑制"],
    improvementIdeas: ["複数サイズと色のバリアント追加"],
  },
  {
    id: "ui-003",
    slug: "animated-contact-form",
    title: "Animated Contact Form",
    description: "入力補助、バリデーション、送信状態まで含む問い合わせフォームUI。",
    category: "form-ui",
    tags: ["form", "validation", "contact"],
    emotionTags: ["実務向き", "サクサク", "制作会社っぽい"],
    technologies: ["React", "TypeScript", "React Hook Form", "Zod", "MSW"],
    difficulty: 4,
    thumbnailUrl: "/globe.svg",
    demoType: "component",
    status: "published",
    isFeatured: false,
    createdAt: "2026-05-21",
    updatedAt: "2026-05-21",
    implementationNotes: ["入力中ラベルとエラー表示を干渉させない。", "送信成功・失敗をMSWで再現する。"],
    learningPoints: ["フォーム状態管理", "スキーマバリデーション", "非同期UI"],
    improvementIdeas: ["確認画面つきフォームへの拡張"],
  },
  {
    id: "ui-004",
    slug: "command-menu",
    title: "Command Menu",
    description: "Cmd/Ctrl + K と / で開ける、検索と操作を集約したキーボードUI。",
    category: "navigation",
    tags: ["command", "keyboard", "navigation"],
    emotionTags: ["サクサク", "実務向き", "ポートフォリオ向き"],
    technologies: ["React", "TypeScript", "Radix UI", "Zustand"],
    difficulty: 4,
    thumbnailUrl: "/next.svg",
    demoType: "component",
    status: "published",
    isFeatured: false,
    createdAt: "2026-05-21",
    updatedAt: "2026-05-21",
    implementationNotes: ["ページ文脈に応じてコマンド候補を変える。", "Escと矢印キー操作を前提に設計する。"],
    learningPoints: ["キーボード操作", "状態管理", "アクセシビリティ"],
    improvementIdeas: ["UI作品検索との統合"],
  },
  {
    id: "ui-005",
    slug: "3d-product-hero",
    title: "3D Product Hero",
    description: "Canvasを遅延読み込みし、3DオブジェクトとCTAを組み合わせるプロダクトヒーロー。",
    category: "three-d",
    tags: ["three", "hero", "product"],
    emotionTags: ["没入感", "近未来", "ポートフォリオ向き"],
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Drei"],
    difficulty: 5,
    thumbnailUrl: "/vercel.svg",
    demoType: "three",
    status: "wip",
    isFeatured: true,
    createdAt: "2026-05-21",
    updatedAt: "2026-05-21",
    implementationNotes: ["初期表示ではCanvasを読み込まない。", "スマホは軽量な代替表示を用意する。"],
    learningPoints: ["3D表現", "遅延読み込み", "パフォーマンス配慮"],
    improvementIdeas: ["実装時にThree.js関連依存を追加する"],
  },
];

export const categories = Array.from(new Set(mockUiItems.map((item) => item.category)));
export const tags = Array.from(new Set(mockUiItems.flatMap((item) => item.tags))).sort();
